version: 2.1
orbs:
  snyk: snyk/snyk@2.0.2

jobs:
  snyk-scan:
    docker:
      - image: circleci/node:12
    steps:    
      - checkout
      - run: npm install --force
      - snyk/scan

workflows:
  build-snyk:
    jobs:
      - snyk-scan
          fail-on-issues: false
      - run:
          name: Run Unit Tests
          command: |
